[build]
  command = "npm run build"
  publish = ".next"
  ignore = "grep -q 'app/api/companies/\\[id\\]/route' git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"
  NEXT_PUBLIC_SKIP_TYPE_CHECK = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.cache]
  paths = [
    "node_modules/.cache",
    ".next/cache"
  ] 